steps:
# Build and push images.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - -c
  - |
    # Build base, FROM base, and newbase
    docker build -t gcr.io/$PROJECT_ID/rebase-base -t base -f Dockerfile.base .
    docker build -t gcr.io/$PROJECT_ID/rebase-test .
    docker build -t gcr.io/$PROJECT_ID/rebase-newbase -f Dockerfile.newbase .

    # Check that image FROM base does what base would have it do.
    docker run gcr.io/$PROJECT_ID/rebase-test | grep foo

    # Push all images. Rebasing is performed on images already in the registry.
    docker push gcr.io/$PROJECT_ID/rebase-base
    docker push gcr.io/$PROJECT_ID/rebase-test
    docker push gcr.io/$PROJECT_ID/rebase-newbase

# Perform rebase in the registry, producing image tagged :rebased.
- name: 'gcr.io/test-argo/rebase'
  args:
  - --original=gcr.io/$PROJECT_ID/rebase-test:latest
  - --old_base=gcr.io/$PROJECT_ID/rebase-base:latest
  - --new_base=gcr.io/$PROJECT_ID/rebase-newbase:latest
  - --rebased=gcr.io/$PROJECT_ID/rebase-test:rebased

# Check that rebased image does what *newbase* would have it do.
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - -c
  - docker run gcr.io/$PROJECT_ID/rebase-test:rebased | grep bar
